"use strict";

/**
 * CodeManager is a static class that controls block execution. It also moves the BlockStack that the user is dragging,
 * keeps track of variables/lists, and passes messages to Blocks/Stacks/Slots/Tabs
 */
function Language() {

};


Language.lang = "US";
Language.langs = ["US", "ES"];

Language.US = {
    "Delete_recording_question":"Are you sure you would like to delete the current recording?",
    "Name_error_blank": "Name cannot be blank. Enter a file name.",
    "Name_error_invalid_characters": "The following characters cannot be included in file names: \n",
    "Name_error_already_exists": "\" already exists.  Enter a different name.",
    "Confirm_delete_question": "Are you sure you want to delete this file?",
    "Name_duplicate_file": "Enter name for duplicate file",
    "Disconnect_account_question": "Disconnect account?",
    "Files_will_remain": "Downloaded files will remain on this device.",
    "Open_before_recording": "Please open a project before recording",
    "Grant_permission": "Please grant recording permissions to the BirdBlox app in settings",
    "List_delete_question": "Are you sure you want to delete this list?",
    "Variable_delete_question": "Are you sure you want to delete this variable?",
    "Device_firmware:": "\nDevice firmware version: ",
    "Required_firmware:": "\nRequired firmware version: ",
    "CompassCalibrate":"Compass Calibrate",
    "Compass": "Compass",
    "Screen_Up": "Screen Up",
    "Screen_Down": "Screen Down",
    "Tilt_Left": "Tilt Left",
    "Tilt_Right": "Tilt Right",
    "Logo_Up": "Logo Up",
    "Logo_Down": "Logo Down",
    "Shake": "Shake",
    "Button": "Button",
    "Magnetometer": "Magnetometer",
    "Accelerometer": "Accelerometer",
    "Print": "Print",
    "Display": "Display",
    "Distance": "Distance",
    "Dial": "Dial",
    "Light": "Light",
    "Sound": "Sound",
    "Other": "Other",
    "Play_Note": "Play Note",
    "for": "for",
    "Beats": "Beats",
    "Position_Servo": "Position Servo",
    "Rotation_Servo": "Rotation Servo",
    "LED": "LED",
    "Tri_LED": "Tri-LED",
    "R": "R",
    "G": "G",
    "B": "B",
    "Servo": "Servo",
    "Vibration":"Vibration",
    "Motor":"Motor",
    "Temperature_C":"Temperature C",
    "Temperature_F":"Temperature F",
    "Knob": "Knob",
    "Device_Shaken":"Device Shaken",
    "Device_SSID":"Device SSID",
    "Device_Pressure":"Device Pressure",
    "Device_Relative_Altitude":"Device Relative Altitude",
    "Device_Orientation":"Device Orientation",
    "Device":"Device",
    "Acceleration":"Acceleration",
    "Latitude":"Latitude",
    "Longitude":"Longitude",
    "when":"when",
    "tapped":"tapped",
    "when_I_receive":"when I receive",
    "wait_until":"wait until",
    "repeat_forever":"repeat forever",
    "repeat":"repeat",
    "repeat_until":"repeat until",
    "if":"if",
    "broadcast":"broadcast",
    "and_wait":"and wait",
    "stop":"stop",
    "all":"all",
    "this_script":"this script",
    "all_but_this_script":"all but this script",
    "message":"message",
    "wait":"wait",
    "secs":"secs",
    "else":"else",
    "item":"item",
    "of":"of",
    "length":"length",
    "contains":"contains",
    "play_sound":"play sound",
    "play_sound_until_done":"play sound until done",
    "play_recording":"play recording",
    "play_recording_until_done":"play recording until done",
    "stop_all_sounds":"stop all sounds",
    "rest_for":"rest for",
    "for":"for",
    "play_note":"play note",
    "change_tempo_by":"change tempo by",
    "set_tempo_to":"set tempo to",
    "tempo":"tempo",
    "round":"round",
    "mod":"mod",
    "pick_random":"pick random",
    "to":"to",
    "and":"and",
    "or":"or",
    "not":"not",
    "true":"true",
    "false":"false",
    "letter":"letter",
    "join":"join",
    "split":"split",
    "by":"by",
    "whitespace":"whitespace",
    "number":"number",
    "text":"text",
    "boolean":"boolean",
    "list":"list",
    "invalid_number":"invalid number",
    "Edit_Text":"Edit Text",
    "is":"is",
    "a":"a",
    "reset_timer":"reset timer",
    "and_wait":"and wait",
    "ask": "ask",
    "at":"at",
    "Position":"Position",
    "current":"current",
    "year":"year",
    "month":"month",
    "date":"date",
    "hour":"hour",
    "minute":"minute",
    "second":"second",
    "day_of_the_week":"day of the week",
    "time_in_milliseconds":"time in milliseconds",
    "answer":"answer",
    "timer":"timer",
    "Record_Sounds":"Record Sound",
    "Create_Variable":"Create Variable",
    "Create_List":"Create List",
    "Zoom_in":"Zoom in",
    "Zoom_out":"Zoom out",
    "Reset_zoom":"Reset zoom",
    "Disable_snap_noise":"Disable snap noise",
    "Enable_snap_noise":"Enable snap noise",
    "Send_debug_log":"Send debug log",
    "Show_debug_menu":"Show debug menu",
    "Disconnect_Device":"Disconnect Device",
    "Connect_Device":"Connect Device",
    "Connect_Multiple":"Connect Multiple",
    "New":"New",
    "Open":"Open",
    "No_saved_programs":"No saved programs",
    "On_Device":"On Device",
    "Cloud":"Cloud",
    "Device limit reached":"Device limit reached",
    "Tap_record_to_start":"Tap record to start",
    "Done":"Done",
    "Loading":"Loading",
    "Tap":"Tap",
    "to_connect":"to connect",
    "Cancel":"Cancel",
    "Scanning_for_devices":"Scanning for devices",
    "Sign_in":"Sign in",
    "world":"world",
    "hello":"hello",
    "what_your_name":"What's your name?",
    "Question":"Question",
    "bpm":"bpm",
    "Total": "Total",
    "set":"set",
    "change":"change",
    "add":"add",
    "thing":"thing",
    "delete":"delete",
    "insert":"insert",
    "at":"at",
    "replace_item":"replace item",
    "with":"with",
    "copy":"copy",
    "Robots":"Robots",
    "Operators":"Operators",
    "Tablet":"Tablet",
    "Control":"Control",
    "Variables":"Variables",
    "any_message":"any message",
    "new":"new",
    "Port":"Port",
    "last":"last",
    "random":"random",
    "Enter_text":"Enter text",
    "Connection_Failure": "Connection Failure",
    "Dismiss":"Dismiss",
    "Connection_failed_try_again":"Connection failed, please try again.",
    "Enter_variable_name":"Enter variable name",
    "Enter_list_name":"Enter list name",
    "not_a_valid_number":"not a valid number",
    "not_connected":"not connected",
    "Firmware_incompatible":"Firmware incompatible",
    "Update_firmware":"Update firmware",
    "Rename_list":"Rename list",
    "Enter_list_name":"Enter list name",
    "Delete_list":"Delete list",
    "Dont_delete":"Don't delete",
    "Delete":"Delete",
    "Permission_denied":"Permission denied",
    "Dismiss":"Dismiss",
    "Continue_recording": "Continue recording",
    "Record_sounds":"Record sounds",
    "New_program":"New program",
    "Enter_file_name":"Enter file name",
    "Saving":"Saving",
    "Name":"Name",
    "Rename":"Rename",
    "Duplicate":"Duplicate",
    "Disconnect_account":"Disconnect account",
    "Dont_disconnect":"Don't disconnect",
    "Disconnect":"Disconnect",
    "Recordings":"Recordings",
    "Record":"Record",
    "Discard":"Discard",
    "Stop":"Stop",
    "Pause":"Pause",
    "remaining":"remaining",
    "No_project_open":"No project open",
    "OK":"OK",
    "Edit_text":"Edit text",
    "Share":"Share",
    "Rename_variable":"Rename variable",
    "Enter_variable_name":"Enter variable name",
    "Delete_variable":"Delete variable"
};


Language.ES = {
    "Delete_recording_question":"ESP",
    "Name_error_blank": "ESP",
    "Name_error_invalid_characters": "ESP",
    "Name_error_already_exists": "ESP",
    "Confirm_delete_question": "ESP",
    "Name_duplicate_file": "ESP",
    "Disconnect_account_question": "ESP",
    "Files_will_remain": "ESP",
    "Open_before_recording": "ESP",
    "Grant_permission": "ESP",
    "List_delete_question": "ESP",
    "Variable_delete_question": "ESP",
    "Device_firmware:": "ESP",
    "Required_firmware:": "ESP",
    "CompassCalibrate":"ESP",
    "Compass": "ESP",
    "Screen_Up": "ESP",
    "Screen_Down": "ESP",
    "Tilt_Left": "ESP",
    "Tilt_Right": "ESP",
    "Logo_Up": "ESP",
    "Logo_Down": "ESP",
    "Shake": "ESP",
    "Button": "ESP",
    "Magnetometer": "ESP",
    "Accelerometer": "ESP",
    "Print": "ESP",
    "Display": "ESP",
    "Distance": "ESP",
    "Dial": "ESP",
    "Light": "ESP",
    "Sound": "ESP",
    "Other": "ESP",
    "Play_Note": "ESP",
    "for": "ESP",
    "Beats": "ESP",
    "Position_Servo": "ESP",
    "Rotation_Servo": "ESP",
    "LED": "ESP",
    "Tri_LED": "ESP",
    "R": "ESP",
    "G": "ESP",
    "B": "ESP",
    "Servo": "ESP",
    "Vibration":"ESP",
    "Motor":"ESP",
    "Temperature_C":"ESP",
    "Temperature_F":"ESP",
    "Knob": "ESP",
    "Device_Shaken":"ESP",
    "Device_SSID":"ESP",
    "Device_Pressure":"ESP",
    "Device_Relative_Altitude":"ESP",
    "Device_Orientation":"ESP",
    "Device":"ESP",
    "Acceleration":"ESP",
    "Latitude":"ESP",
    "Longitude":"ESP",
    "when":"ESP",
    "tapped":"ESP",
    "when_I_receive":"ESP",
    "wait_until":"ESP",
    "repeat_forever":"ESP",
    "repeat":"ESP",
    "repeat_until":"ESP",
    "if":"ESP",
    "broadcast":"ESP",
    "and_wait":"ESP",
    "stop":"ESP",
    "all":"ESP",
    "this_script":"ESP",
    "all_but_this_script":"ESP",
    "message":"ESP",
    "wait":"ESP",
    "secs":"ESP",
    "else":"ESP",
    "item":"ESP",
    "of":"ESP",
    "length":"ESP",
    "contains":"ESP",
    "play_sound":"ESP",
    "play_sound_until_done":"ESP",
    "play_recording":"ESP",
    "play_recording_until_done":"ESP",
    "stop_all_sounds":"ESP",
    "rest_for":"ESP",
    "for":"ESP",
    "play_note":"ESP",
    "change_tempo_by":"ESP",
    "set_tempo_to":"ESP",
    "tempo":"ESP",
    "round":"ESP",
    "mod":"ESP",
    "pick_random":"ESP",
    "to":"ESP",
    "and":"ESP",
    "or":"ESP",
    "not":"ESP",
    "true":"ESP",
    "false":"ESP",
    "letter":"ESP",
    "join":"ESP",
    "split":"ESP",
    "by":"ESP",
    "whitespace":"ESP",
    "number":"ESP",
    "text":"ESP",
    "boolean":"ESP",
    "list":"ESP",
    "invalid_number":"ESP",
    "Edit_Text":"ESP",
    "is":"ESP",
    "a":"ESP",
    "reset_timer":"ESP",
    "and_wait":"ESP",
    "ask": "ESP",
    "at":"ESP",
    "Position":"ESP",
    "current":"ESP",
    "year":"ESP",
    "month":"ESP",
    "date":"ESP",
    "hour":"ESP",
    "minute":"ESP",
    "second":"ESP",
    "day_of_the_week":"ESP",
    "time_in_milliseconds":"ESP",
    "answer":"ESP",
    "timer":"ESP",
    "Record_Sounds":"ESP",
    "Create_Variable":"ESP",
    "Create_List":"ESP",
    "Zoom_in":"ESP",
    "Zoom_out":"ESP",
    "Reset_zoom":"ESP",
    "Disable_snap_noise":"ESP",
    "Enable_snap_noise":"ESP",
    "Send_debug_log":"ESP",
    "Show_debug_menu":"ESP",
    "Disconnect_Device":"ESP",
    "Connect_Device":"ESP"
    "Connect_Multiple":"ESP",
    "New":"ESP",
    "Open":"ESP",
    "No_saved_programs":"ESP",
    "On_Device":"ESP",
    "Cloud":"ESP",
    "Device limit reached":"ESP",
    "Tap_record_to_start":"ESP",
    "Done":"ESP",
    "Loading":"ESP",
    "Tap":"ESP",
    "to_connect":"ESP",
    "Cancel":"ESP",
    "Scanning_for_devices":"ESP",
    "Sign_in":"ESP",
    "world":"ESP",
    "hello":"ESP",
    "what_your_name":"ESP",
    "Question":"ESP",
    "bpm":"ESP",
    "Total": "ESP",
    "set":"ESP",
    "change":"ESP",
    "add":"ESP",
    "thing":"ESP",
    "delete":"ESP",
    "insert":"ESP",
    "at":"ESP",
    "replace_item":"ESP",
    "with":"ESP",
    "copy":"ESP",
    "Robots":"ESP",
    "Operators":"ESP",
    "Tablet":"ESP",
    "Control":"ESP",
    "Variables":"ESP",
    "any_message":"ESP",
    "new":"ESP",
    "Port":"ESP",
    "last":"ESP",
    "random":"ESP",
    "Enter_text":"ESP",
    "Connection_Failure": "ESP",
    "Dismiss":"ESP",
    "Connection_failed_try_again":"ESP",
    "Enter_variable_name":"ESP",
    "Enter_list_name":"ESP",
    "not_a_valid_number":"ESP",
    "not_connected":"ESP",
    "Firmware_incompatible":"ESP",
    "Update_firmware":"ESP",
    "Rename_list":"ESP",
    "Enter_list_name":"ESP",
    "Delete_list":"ESP",
    "Dont_delete":"ESP",
    "Delete":"ESP",
    "Permission_denied":"ESP",
    "Dismiss":"ESP",
    "Continue_recording": "ESP",
    "Record_sounds":"ESP",
    "New_program":"ESP",
    "Enter_file_name":"ESP",
    "Saving":"ESP",
    "Name":"ESP",
    "Rename":"ESP",
    "Duplicate":"ESP",
    "Disconnect_account":"ESP",
    "Dont_disconnect":"ESP",
    "Disconnect":"ESP",
    "Recordings":"ESP",
    "Record":"ESP",
    "Discard":"ESP",
    "Stop":"ESP",
    "Pause":"ESP",
    "remaining":"ESP",
    "No_project_open":"ESP",
    "OK":"ESP",
    "Edit_text":"ESP",
    "Share":"ESP",
    "Rename_variable":"ESP",
    "Enter_variable_name":"ESP",
    "Delete_variable":"ESP"
};


Language.setLanguage = function(lang) {
    if (Language.langs.indexOf(lang) === -1) {
        Language.lang = "US";
    } else {
        Language.lang = lang;
    }
}

Language.getLanguage = function () {
    return "Language." + Language.lang + ".";
}

Language.getStr = function(str) {
    let translatedStr = eval(Language.getLanguage() + str);
    if (translatedStr != null) {
        return translatedStr;
    } else {
        return "Translation required";
    }
}
