"use strict";

/**
 * Language is a static class that provides translation for blocks.
 */
function Language() {

};

//The default language for the app is english
Language.lang = "en";

/* The list of languages that are currently supported by birdblox. Any new language should be added
to this list */
Language.langs = ["en", "zh", "fr", "es", "nl"];


/* The disctionary for English, an underscore is necessary to separate the words in keys.
   If translation for a word is not found in the dictionary.
   No translation will be shown for the block.*/
Language.en = {
    "CompassCalibrate":"Compass Calibrate",
    "Compass": "Compass",
    "Screen_Up": "Screen Up",
    "Screen_Down": "Screen Down",
    "Tilt_Left": "Tilt Left",
    "Tilt_Right": "Tilt Right",
    "Logo_Up": "Logo Up",
    "Logo_Down": "Logo Down",
    "Shake": "Shake",
    "Button": "Button",
    "Magnetometer": "Magnetometer",
    "Accelerometer": "Accelerometer",
    "Print": "Print",
    "Display": "Display",
    "Distance": "Distance",
    "Dial": "Dial",
    "Light": "Light",
    "Sound": "Sound",
    "Other": "Other",
    "Play_Note": "Play Note",
    "for": "for",
    "Beats": "Beats",
    "Position_Servo": "Position Servo",
    "Rotation_Servo": "Rotation Servo",
    "LED": "LED",
    "Tri_LED": "Tri-LED",
    "R": "R",
    "G": "G",
    "B": "B",
    "Servo": "Servo",
    "Vibration":"Vibration",
    "Motor":"Motor",
    "Temperature_C":"Temperature C",
    "Temperature_F":"Temperature F",
    "Knob": "Knob",
    "Device_Shaken":"Device Shaken",
    "Device_SSID":"Device SSID",
    "Device_Pressure":"Device Pressure",
    "Device_Relative_Altitude":"Device Relative Altitude",
    "Device_Orientation":"Device Orientation",
    "Device":"Device",
    "Acceleration":"Acceleration",
    "Latitude":"Latitude",
    "Longitude":"Longitude",
    "when":"when",
    "tapped":"tapped",
    "when_I_receive":"when I receive",
    "wait_until":"wait until",
    "repeat_forever":"repeat forever",
    "repeat":"repeat",
    "repeat_until":"repeat until",
    "if":"if",
    "broadcast":"broadcast",
    "and_wait":"and wait",
    "stop":"stop",
    "all":"all",
    "this_script":"this script",
    "all_but_this_script":"all but this script",
    "message":"message",
    "wait":"wait",
    "secs":"secs",
    "else":"else",
    "item":"item",
    "of":"of",
    "length":"length",
    "contains":"contains",
    "play_sound":"play sound",
    "play_sound_until_done":"play sound until done",
    "play_recording":"play recording",
    "play_recording_until_done":"play recording until done",
    "stop_all_sounds":"stop all sounds",
    "rest_for":"rest for",
    "for":"for",
    "play_note":"play note",
    "change_tempo_by":"change tempo by",
    "set_tempo_to":"set tempo to",
    "tempo":"tempo",
    "round":"round",
    "mod":"mod",
    "pick_random":"pick random",
    "to":"to",
    "and":"and",
    "or":"or",
    "not":"not",
    "true":"true",
    "false":"false",
    "letter":"letter",
    "join":"join",
    "split":"split",
    "by":"by",
    "whitespace":"whitespace",
    "number":"number",
    "text":"text",
    "boolean":"boolean",
    "list":"list",
    "invalid_number":"invalid number",
    "Edit_Text":"Edit Text",
    "is":"is",
    "a":"a",
    "reset_timer":"reset timer",
    "and_wait":"and wait",
    "ask": "ask",
    "at":"at",
    "Position":"Position",
    "current":"current",
    "year":"year",
    "month":"month",
    "date":"date",
    "hour":"hour",
    "minute":"minute",
    "second":"second",
    "day_of_the_week":"day of the week",
    "time_in_milliseconds":"time in milliseconds",
    "answer":"answer",
    "timer":"timer",
    "Record_Sounds":"Record Sound",
    "Create_Variable":"Create Variable",
    "Create_List":"Create List",
    "Zoom_in":"Zoom in",
    "Zoom_out":"Zoom out",
    "Reset_zoom":"Reset zoom",
    "Disable_snap_noise":"Disable snap noise",
    "Enable_snap_noise":"Enable snap noise",
    "Send_debug_log":"Send debug log",
    "Show_debug_menu":"Show debug menu",
    "Disconnect_Device":"Disconnect Device",
    "Connect_Device":"Connect Device",
    "Connect_Multiple":"Connect Multiple",
    "New":"New",
    "Open":"Open",
    "No_saved_programs":"No saved programs",
    "On_Device":"On Device",
    "Cloud":"Cloud",
    "Device limit reached":"Device limit reached",
    "Tap_record_to_start":"Tap record to start",
    "Done":"Done",
    "Loading":"Loading",
    "Tap":"Tap",
    "to_connect":"to connect",
    "Cancel":"Cancel",
    "Scanning_for_devices":"Scanning for devices",
    "Sign_in":"Sign_in",
    "read":"Read",
    "write":"Write",
    "pin":"Pin",
    "Percent":"Percent"
};

/* The disctionary for Chinese, an underscore is necessary to separate the words in keys.*/
Language.zh = {
    "CompassCalibrate":"CN",
    "Compass": "CN",
    "Screen_Up": "CN",
    "Screen_Down": "CN",
    "Tilt_Left": "CN",
    "Tilt_Right": "CN",
    "Logo_Up": "CN",
    "Logo_Down": "CN",
    "Shake": "CN",
    "Button": "CN",
    "Magnetometer": "CN",
    "Accelerometer": "CN",
    "Print": "CN",
    "Display": "CN",
    "Distance": "CN",
    "Dial": "CN",
    "Light": "CN",
    "Sound": "CN",
    "Other": "CN",
    "Play_Note": "CN",
    "for": "CN",
    "Beats": "CN",
    "Position_Servo": "CN",
    "Rotation_Servo": "CN",
    "LED": "CN",
    "Tri_LED": "CN",
    "R": "R",
    "G": "G",
    "B": "B",
    "Servo": "CN",
    "Vibration":"CN",
    "Motor":"CN",
    "Temperature_C":"CN",
    "Temperature_F":"CN",
    "Knob": "CN",
    "Device_Shaken":"CN",
    "Device_SSID":"CN",
    "Device_Pressure":"CN",
    "Device_Relative_Altitude":"CN",
    "Device_Orientation":"CN",
    "Device":"CN",
    "Acceleration":"CN",
    "Latitude":"CN",
    "Longitude":"CN",
    "when":"CN",
    "tapped":"CN",
    "when_I_receive":"CN",
    "wait_until":"CN",
    "repeat_forever":"CN",
    "repeat":"CN",
    "repeat_until":"CN",
    "if":"CN",
    "broadcast":"CN",
    "and_wait":"CN",
    "stop":"CN",
    "all":"CN",
    "this_script":"CN",
    "all_but_this_script":"CN",
    "message":"CN",
    "wait":"CN",
    "secs":"CN",
    "else":"CN",
    "item":"CN",
    "of":"CN",
    "length":"CN",
    "contains":"CN",
    "play_sound":"CN",
    "play_sound_until_done":"CN",
    "play_recording":"CN",
    "play_recording_until_done":"CN",
    "stop_all_sounds":"CN",
    "rest_for":"CN",
    "for":"CN",
    "play_note":"CN",
    "change_tempo_by":"CN",
    "set_tempo_to":"CN",
    "tempo":"CN",
    "round":"CN",
    "mod":"CN",
    "pick_random":"CN",
    "to":"CN",
    "and":"CN",
    "or":"CN",
    "not":"CN",
    "true":"CN",
    "false":"CN",
    "letter":"CN",
    "join":"CN",
    "split":"CN",
    "by":"CN",
    "whitespace":"CN",
    "number":"CN",
    "text":"CN",
    "boolean":"CN",
    "list":"CN",
    "invalid_number":"CN",
    "Edit_Text":"CN",
    "is":"CN",
    "a":"CN",
    "reset_timer":"CN",
    "and_wait":"CN",
    "ask": "CN",
    "at":"CN",
    "Position":"CN",
    "current":"CN",
    "year":"CN",
    "month":"CN",
    "date":"CN",
    "hour":"CN",
    "minute":"CN",
    "second":"CN",
    "day_of_the_week":"CN",
    "time_in_milliseconds":"CN",
    "answer":"CN",
    "timer":"CN",
    "Record_Sounds":"CN",
    "Create_Variable":"CN",
    "Create_List":"CN",
    "Zoom_in":"CN",
    "Zoom_out":"CN",
    "Reset_zoom":"CN",
    "Disable_snap_noise":"CN",
    "Enable_snap_noise":"CN",
    "Send_debug_log":"CN",
    "Show_debug_menu":"CN",
    "Disconnect_Device":"CN",
    "Connect_Device":"CN",
    "Connect_Multiple":"CN Connect Multiple",
    "New":"CN",
    "Open":"CN",
    "No_saved_programs":"CN",
    "On_Device":"CN",
    "Cloud":"CN",
    "Device limit reached":"CN",
    "Tap_record_to_start":"CN",
    "Done":"CN",
    "Loading":"CN",
    "Tap":"CN",
    "to_connect":"CN",
    "Cancel":"CN",
    "Scanning_for_devices":"CN",
    "Sign_in":"CN"
}


/* The disctionary for Spanish, an underscore is necessary to separate the words in keys.*/
Language.es = {
    "CompassCalibrate":"ESP",
    "Compass": "ESP",
    "Screen_Up": "ESP",
    "Screen_Down": "ESP",
    "Tilt_Left": "ESP",
    "Tilt_Right": "ESP",
    "Logo_Up": "ESP",
    "Logo_Down": "ESP",
    "Shake": "ESP",
    "Button": "ESP",
    "Magnetometer": "ESP",
    "Accelerometer": "ESP",
    "Print": "ESP",
    "Display": "ESP",
    "Distance": "ESP",
    "Dial": "ESP",
    "Light": "ESP",
    "Sound": "ESP",
    "Other": "ESP",
    "Play_Note": "ESP",
    "for": "ESP",
    "Beats": "ESP",
    "Position_Servo": "ESP",
    "Rotation_Servo": "ESP",
    "LED": "ESP",
    "Tri_LED": "ESP",
    "R": "R",
    "G": "G",
    "B": "B",
    "Servo": "ESP",
    "Vibration":"ESP",
    "Motor":"ESP",
    "Temperature_C":"ESP",
    "Temperature_F":"ESP",
    "Knob": "ESP",
    "Device_Shaken":"ESP",
    "Device_SSID":"ESP",
    "Device_Pressure":"ESP",
    "Device_Relative_Altitude":"ESP",
    "Device_Orientation":"ESP",
    "Device":"ESP",
    "Acceleration":"ESP",
    "Latitude":"ESP",
    "Longitude":"ESP",
    "when":"ESP",
    "tapped":"ESP",
    "when_I_receive":"ESP",
    "wait_until":"ESP",
    "repeat_forever":"ESP",
    "repeat":"ESP",
    "repeat_until":"ESP",
    "if":"ESP",
    "broadcast":"ESP",
    "and_wait":"ESP",
    "stop":"ESP",
    "all":"ESP",
    "this_script":"ESP",
    "all_but_this_script":"ESP",
    "message":"ESP",
    "wait":"ESP",
    "secs":"ESP",
    "else":"ESP",
    "item":"ESP",
    "of":"ESP",
    "length":"ESP",
    "contains":"ESP",
    "play_sound":"ESP",
    "play_sound_until_done":"ESP",
    "play_recording":"ESP",
    "play_recording_until_done":"ESP",
    "stop_all_sounds":"ESP",
    "rest_for":"ESP",
    "for":"ESP",
    "play_note":"ESP",
    "change_tempo_by":"ESP",
    "set_tempo_to":"ESP",
    "tempo":"ESP",
    "round":"ESP",
    "mod":"ESP",
    "pick_random":"ESP",
    "to":"ESP",
    "and":"ESP",
    "or":"ESP",
    "not":"ESP",
    "true":"ESP",
    "false":"ESP",
    "letter":"ESP",
    "join":"ESP",
    "split":"ESP",
    "by":"ESP",
    "whitespace":"ESP",
    "number":"ESP",
    "text":"ESP",
    "boolean":"ESP",
    "list":"ESP",
    "invalid_number":"ESP",
    "Edit_Text":"ESP",
    "is":"ESP",
    "a":"ESP",
    "reset_timer":"ESP",
    "and_wait":"ESP",
    "ask": "ESP",
    "at":"ESP",
    "Position":"ESP",
    "current":"ESP",
    "year":"ESP",
    "month":"ESP",
    "date":"ESP",
    "hour":"ESP",
    "minute":"ESP",
    "second":"ESP",
    "day_of_the_week":"ESP",
    "time_in_milliseconds":"ESP",
    "answer":"ESP",
    "timer":"ESP",
    "Record_Sounds":"ESP",
    "Create_Variable":"ESP",
    "Create_List":"ESP",
    "Zoom_in":"ESP",
    "Zoom_out":"ESP",
    "Reset_zoom":"ESP",
    "Disable_snap_noise":"ESP",
    "Enable_snap_noise":"ESP",
    "Send_debug_log":"ESP",
    "Show_debug_menu":"ESP",
    "Disconnect_Device":"ESP",
    "Connect_Device":"ESP",
    "Connect_Multiple":"ESP Connect Multiple",
    "New":"ESP",
    "Open":"ESP",
    "No_saved_programs":"ESP",
    "On_Device":"ESP",
    "Cloud":"ESP",
    "Device limit reached":"ESP",
    "Tap_record_to_start":"ESP",
    "Done":"ESP",
    "Loading":"ESP",
    "Tap":"ESP",
    "to_connect":"ESP",
    "Cancel":"ESP",
    "Scanning_for_devices":"ESP",
    "Sign_in":"ESP"
}

/* The disctionary for French, an underscore is necessary to separate the words in keys.*/
Language.fr = {
    "Delete_recording_question":"Supprimer l'enregistrement?",
    "Name_error_blank":"Le nom ne peut pas être vide. Entrez un nom de fichier",
    "Name_error_invalid_characters":"Les caractères suivants ne peuvent pas être inclus dans les noms de fichiers: \n",
    "Name_error_already_exists":"\" existe déjà. Entrez un nom différent.",
    "Confirm_delete_question":"Supprimer le fichier?",
    "Name_duplicate_file":"Entrez le nom du fichier en double",
    "Disconnect_account_question":"Déconnecter le compte?",
    "Grant_permission":"Accorder une autorisation d'enregistrement à BirdBlox dans les Paramètres",
    "List_delete_question":"Supprimer la liste?",
    "Variable_delete_question":"Supprimer la variable?",
    "Device_firmware:":"Version du firmware du périphérique:",
    "Required_firmware:":"Version du firmware requise:",
    "CompassCalibrate":"Calibrer le compas",
    "Compass":"Compas",
    "Screen_Up":"Écran vers le haut",
    "Screen_Down":"Écran vers le bas",
    "Tilt_Left":"Incliner à gauche",
    "Tilt_Right":"Incliner à droite",
    "Logo_Up":"Logo vers le haut",
    "Logo_Down":"Logo vers le bas",
    "Shake":"Secouer",
    "Button":"Bouton",
    "Magnetometer":"Magnétomètre",
    "Accelerometer":"Accéléromètre",
    "Print":"Imprimer",
    "Display":"Display",
    "Distance":"Distance",
    "Dial":"Cadran",
    "Light":"Lumière",
    "Sound":"Son",
    "Other":"Autre",
    "Play_Note":"Jouer la note",
    "for":"pour",
    "Beats":"Battement",
    "Position_Servo":"Position Servo",
    "Rotation_Servo":"Rotation Servo",
    "LED":"LED",
    "Tri_LED":"Tri-LED",
    "R":"R",
    "G":"G",
    "B":"B",
    "Servo":"Servo",
    "Vibration":"Vibration",
    "Motor":"Moteur",
    "Temperature_C":"Température C",
    "Temperature_F":"Température F",
    "Knob":"Bouton",
    "Device_Shaken":"Tablette secouée",
    "Device_SSID":"Tablette SSID",
    "Device_Pressure":"Tablette Pression",
    "Device_Relative_Altitude":"Tablette Altitude Relative ",
    "Device_Orientation":"Tablette Orientation",
    "Device":"Tablette",
    "Acceleration":"Accélération",
    "Latitude":"Latitude",
    "Longitude":"Longitude",
    "when":"quand",
    "tapped":"tapoter",
    "when_I_receive":"quand je reçois",
    "wait_until":"attend jusqu'à",
    "repeat_forever":"répéter pour toujours",
    "repeat":"répéter ",
    "repeat_until":"répéter jusqu'à",
    "if":"si ",
    "broadcast":"transmettre",
    "and_wait":"et attendez",
    "stop":"stop",
    "all":"tout",
    "this_script":"ce script",
    "all_but_this_script":"tout sauf ce script",
    "message":"message",
    "wait":"attendez",
    "secs":"secondes",
    "else":"autre",
    "item":"item",
    "of":"ou",
    "length":"longueur",
    "contains":"contient",
    "play_sound":"jouer le son",
    "play_sound_until_done":"jouer le son jusqu'à la fin",
    "play_recording":"jouer l' enregistrement",
    "play_recording_until_done":"jouer l' enregistrement jusqu'à la fin",
    "stop_all_sounds":"arrêter tous les sons",
    "rest_for":"reposez pour",
    "for":"pour",
    "play_note":"jouer la note",
    "change_tempo_by":"changer le tempo de",
    "set_tempo_to":"régler le tempo sur",
    "tempo":"tempo",
    "round":"round",
    "mod":"modulo",
    "pick_random":"choisir au hasard",
    "to":"à",
    "and":"et",
    "or":"ou",
    "not":"non",
    "true":"vrai",
    "false":"faux",
    "letter":"lettre",
    "join":"joindre",
    "split":"diviser",
    "by":"avec",
    "whitespace":"espace blanc",
    "number":"numéro",
    "text":"texte",
    "boolean":"booléen",
    "list":"liste",
    "invalid_number":"numéro invalide",
    "Edit_text":"Éditer le texte",
    "is":"est",
    "a":"a",
    "reset_timer":"réinitialiser la minuterie",
    "and_wait":"et attendez",
    "ask":"demande",
    "at":"à",
    "Position":"Position",
    "current":"actuel",
    "year":"année",
    "month":"mois",
    "date":"date",
    "hour":"heure",
    "minute":"minute",
    "second":"seconde",
    "day_of_the_week":"jour de la semaine",
    "time_in_milliseconds":"temps en millisecondes",
    "answer":"réponse",
    "timer":"minuterie",
    "Record_Sounds":"Enregistrer le son",
    "Create_Variable":"Créer une variable",
    "Create_List":"Créer une liste",
    "Zoom_in":"Agrandir",
    "Zoom_out":"Dézoomer",
    "Reset_zoom":"Réinitialiser le zoom",
    "Disable_snap_noise":"Désactiver le bruit d'accrochage",
    "Enable_snap_noise":"Activer le bruit d'accrochage",
    "Send_debug_log":"Envoyer un journal de débogage",
    "Show_debug_menu":"Afficher le menu de débogage",
    "Disconnect_Device":"Déconnecter le périphérique",
    "Connect_Device":"Connecter le périphérique",
    "Connect_Multiple":"Connecter plusieurs",
    "New":"Neuf",
    "Open":"Ouvrir",
    "No_saved_programs":"Aucun programme sauvé",
    "On_Device":"Sur le périphérique",
    "Cloud":"Cloud",
    "Tap_record_to_start":"Tapotez pour commencer l' enregistrement ",
    "Done":"Fini",
    "Loading":"Chargement",
    "Tap":"Tapoter",
    "to_connect":"pour connecter",
    "Cancel":"Annuler",
    "Scanning_for_devices":"Recherche de périphériques",
    "Sign_in":"Se connecter",
    "world":"monde",
    "hello":"bonjour",
    "what_your_name":"Quel est ton nom?",
    "Question":"Question",
    "bpm":"bpm",
    "Total":"Total",
    "set":"fixer",
    "change":"changer",
    "add":"ajouter",
    "thing":"chose",
    "delete":"supprimer",
    "insert":"insérer",
    "at":"à",
    "replace_item":"remplacer l'article",
    "with":"avec",
    "copy":"copier",
    "Robots":"Robots",
    "Operators":"Opérateurs",
    "Tablet":"Tablette",
    "Control":"Contrôle",
    "Variables":"Variables",
    "any_message":"N'importe quel message",
    "port":"Connecteur",
    "last":"Dernier",
    "random":"Au hasard",
    "Enter_text":"Entrez un texte",
    "Connection_Failure":"Échec de connexion",
    "Dismiss":"Rejeter",
    "Connection_failed_try_again":"La connexion a échoué, veuillez réessayer.",
    "Enter_variable_name":"Entrez le nom de la variable",
    "Enter_list_name":"Entrez le nom de la liste",
    "not_a_valid_number":"numéro invalide",
    "not_connected":"pas connecté",
    "Firmware_incompatible":"Firmware incompatible",
    "Update_firmware":"Mettez à jour le firmware",
    "Rename_list":"Renommer la liste",
    "Delete_list":"Supprimer la liste ",
    "Dont_delete":"Ne pas supprimer",
    "Delete":"Supprimer",
    "Permission_denied":"Permission refusée",
    "Continue_recording":"Continuer l' enregistrement",
    "Record_sounds":"Enregistrer les sons",
    "New_program":"Nouveau programme",
    "Enter_file_name":"Entrez le nom du fichier",
    "Saving":"Sauvegarde",
    "Name":"Nom",
    "Rename":"Renommer  ",
    "Duplicate":"Dupliquer",
    "Disconnect_account":"Déconnecter le compte",
    "Dont_disconnect":"Ne pas déconnecter",
    "Disconnect":"Déconnecter  ",
    "Recordings":"Les enregistrements",
    "Record":"Enregistrer  ",
    "Discard":"Jeter",
    "Stop":"Stop",
    "Pause":"Faire une pause",
    "remaining":"restant",
    "No_project_open":"Pas de projet actif",
    "OK":"OK",
    "Share":"Partager",
    "Rename_variable":"Renommez la variable",
    "Delete_variable":"Supprimez la variable",
    "read":"Lire",
    "write":"Écrire",
    "pin":"Broche"
}

Language.nl = {
    "Delete_recording_question":"Opname verwijderen?",
    "Name_error_blank":"Naam moet ingevuld zijn. Voer een bestandsnaam in.",
    "Name_error_invalid_characters":"De volgende lettertekens mogen niet gebruikt worden in bestandsnamen: \n",
    "Name_error_already_exists":"\" bestaat al. Voer een andere naam in.",
    "Confirm_delete_question":"Bestand verwijderen?",
    "Name_duplicate_file":"Voer een naam in voor het gekopieerde bestand",
    "Disconnect_account_question":"Account loskoppelen?",
    "Grant_permission":"Geef toestemming tot opnames aan BirdBlox in Instellingen",
    "List_delete_question":"Lijst verwijderen?",
    "Variable_delete_question":"Variabele verwijderen?",
    "Device_firmware:":"Apparaat firmware versie:",
    "Required_firmware:":"Vereiste firmware versie:",
    "CompassCalibrate":"Kompas Kalibreren",
    "Compass":"Kompas",
    "Screen_Up":"Scherm Omhoog",
    "Screen_Down":"Scherm Omlaag",
    "Tilt_Left":"Naar Links Kantelen",
    "Tilt_Right":"Naar Rechts Kantelen",
    "Logo_Up":"Logo Omhoog",
    "Logo_Down":"Logo Omlaag",
    "Shake":"Schudden",
    "Button":"Knop",
    "Magnetometer":"Magnetometer",
    "Accelerometer":"Accelerometer",
    "Print":"Afdrukken",
    "Display":"Tonen",
    "Distance":"Afstand",
    "Dial":"Draaiknop",
    "Light":"Licht",
    "Sound":"Geluid",
    "Other":"Ander",
    "Play_Note":"Speel Noot",
    "for":"voor",
    "Beats":"Beats",
    "Position_Servo":"Positie Servo",
    "Rotation_Servo":"Rotatie Servo",
    "LED":"LED",
    "Tri_LED":"Tri-LED",
    "R":"R",
    "G":"G",
    "B":"B",
    "Servo":"Servo",
    "Vibration":"Vibratie",
    "Motor":"Motor",
    "Temperature_C":"Temperatuur C",
    "Temperature_F":"Temperatuur F",
    "Knob":"Draaiknop",
    "Device_Shaken":"Tablet Geschud",
    "Device_SSID":"Tablet SSID",
    "Device_Pressure":"Tablet Druk",
    "Device_Relative_Altitude":"Tablet Relatieve Hoogte",
    "Device_Orientation":"Tablet Orientatie",
    "Device":"Tablet",
    "Acceleration":"Acceleratie",
    "Latitude":"Breedtegraad",
    "Longitude":"Lengtegraad",
    "when":"wanneer",
    "tapped":"tikte",
    "when_I_receive":"wanneer ik ontvang",
    "wait_until":"wacht tot",
    "repeat_forever":"herhaal altijd",
    "repeat":"herhaal",
    "repeat_until":"herhaal tot",
    "if":"als",
    "broadcast":"zend uit",
    "and_wait":"en wacht",
    "stop":"stop",
    "all":"alles",
    "this_script":"dit script",
    "all_but_this_script":"alles behalve dit script",
    "message":"signaal",
    "wait":"wacht",
    "secs":"sec.",
    "else":"anders",
    "item":"item",
    "of":"van",
    "length":"lengte",
    "contains":"bevat",
    "play_sound":"speel geluid",
    "play_sound_until_done":"speel geluid tot het einde",
    "play_recording":"speel opname",
    "play_recording_until_done":"speel opname tot het einde",
    "stop_all_sounds":"stop alle geluiden",
    "rest_for":"rust voor",
    "for":"voor",
    "play_note":"speel noot",
    "change_tempo_by":"verander tempo met ",
    "set_tempo_to":"stel tempo in op",
    "tempo":"tempo",
    "round":"afgerond",
    "mod":"modulo",
    "pick_random":"willekeurig getal tussen",
    "to":"tot ",
    "and":"en",
    "or":"of",
    "not":"niet",
    "true":"waar",
    "false":"onwaar",
    "letter":"letter",
    "join":"voeg samen",
    "split":"splits",
    "by":"bij",
    "whitespace":"spatie",
    "number":"getal",
    "text":"tekst",
    "boolean":"booleaans",
    "list":"lijst",
    "invalid_number":"ongeldig getal",
    "Edit_Text":"Bewerk Tekst",
    "is":"is",
    "a":"een",
    "reset_timer":"zet tijd op nul",
    "and_wait":"en wacht",
    "ask":"vraag",
    "at":"op",
    "Position":"Positie",
    "current":"huidig",
    "year":"jaar",
    "month":"maand",
    "date":"datum",
    "hour":"uur",
    "minute":"minuut",
    "second":"seconde",
    "day_of_the_week":"dag van de week",
    "time_in_milliseconds":"tijd in milliseconden",
    "answer":"antwoord",
    "timer":"tijd",
    "Record_Sounds":"Neem Geluid Op",
    "Create_Variable":"Maak een Variabele",
    "Create_List":"Maak een Lijst",
    "Zoom_in":"Inzoomen",
    "Zoom_out":"Uitzoomen",
    "Reset_zoom":"Reset zoom",
    "Disable_snap_noise":"Klikgeluid Uitschakelen",
    "Enable_snap_noise":"Klikgeluid Inschakelen",
    "Send_debug_log":"Stuur foutopsporingslog",
    "Show_debug_menu":"Toon debug-menu",
    "Disconnect_Device":"Ontkoppel Apparaat",
    "Connect_Device":"Verbind Apparaat",
    "Connect_Multiple":"Verbind Meerdere",
    "New":"Nieuw",
    "Open":"Open",
    "No_saved_programs":"Geen opgeslagen programmas",
    "On_Device":"In Apparaat",
    "Cloud":"Cloud",
    "Tap_record_to_start":"Tik om opnemen te starten",
    "Done":"Klaar",
    "Loading":"Laden",
    "Tap":"Tik",
    "to_connect":"verbinden",
    "Cancel":"Annuleer",
    "Scanning_for_devices":"Scannen van apparaten",
    "Sign_in":"Inloggen",
    "world":"wereld",
    "hello":"hallo",
    "what_your_name":"Wat is jouw naam?",
    "Question":"Vraag",
    "bpm":"bpm",
    "Total":"Totaal",
    "set":"maak",
    "change":"verander",
    "add":"voeg toe",
    "thing":"ding",
    "delete":"verwijder",
    "insert":"voeg in",
    "at":"op",
    "replace_item":"vervang item",
    "with":"door",
    "copy":"kopieer",
    "Robots":"Robots",
    "Operators":"Operatoren",
    "Tablet":"Tablet",
    "Control":"Controle",
    "Variables":"Variabelen",
    "any_message":"enige signaal",
    "new":"nieuw",
    "Port":"Poort",
    "last":"laatste",
    "random":"willekeurig",
    "Enter_text":"Tekst invoeren",
    "Connection_Failure":"Verbindingsfout",
    "Dismiss":"Ontslaan",
    "Connection_failed_try_again":"Verbindingsfout, probeer opnieuw",
    "Enter_variable_name":"Voer naam van de variabele in",
    "Enter_list_name":"Voer lijst naam in",
    "not_a_valid_number":"geen geldig getal",
    "not_connected":"niet verbonden",
    "Firmware_incompatible":"Onverenigbare Firmware",
    "Update_firmware":"Update firmware",
    "Rename_list":"Lijst hernoemen",
    "Enter_list_name":"Voer lijst naam in",
    "Delete_list":"Lijst verwijderen",
    "Dont_delete":"Niet verwijderen",
    "Delete":"Verwijderen",
    "Permission_denied":"Geen toestemming",
    "Dismiss":"Ontslaan",
    "Continue_recording":"Doorgaan met opnemen",
    "Record_sounds":"Geluiden opnemen",
    "New_program":"Nieuw programma",
    "Enter_file_name":"Voor een bestandsnaam in",
    "Saving":"Opslaan",
    "Name":"Naam",
    "Rename":"Hernoemen",
    "Duplicate":"Kopiëren",
    "Disconnect_account":"Account Loskoppelen",
    "Dont_disconnect":"Niet Loskoppelen",
    "Disconnect":"Loskoppelen",
    "Recordings":"Opnames",
    "Record":"Opnemen",
    "Discard":"Verwijder",
    "Stop":"Stop",
    "Pause":"Pauze",
    "remaining":"overblijvende",
    "No_project_open":"Geen project open",
    "OK":"OK",
    "Edit_text":"Tekst bewerken",
    "Share":"Share",
    "Rename_variable":"Variabele hernoemen",
    "Enter_variable_name":"Voer variabele naam in",
    "Delete_variable":"Variabele verwijderen",
    "read":"Lees",
    "write":"Schrijf",
    "pin":"Pin"
}

/* The Callback manager receives a request from the backend to set the default language to be
   displayed in the frontend based on the system language preference. If the language is currently
   not supported, english, the default language will be used..*/
Language.setLanguage = function(lang) {
    if (Language.langs.indexOf(lang) === -1) {
        Language.lang = "EN";
    } else {
        Language.lang = lang;
    }
}

/* getLanguage returns the language that is currently being used by the birdblox.*/
Language.getLanguage = function () {
    const userSelectedLang = sessionStorage.getItem("language");
    if (userSelectedLang != undefined && userSelectedLang != null){
      Language.lang = userSelectedLang;
    }
    return "Language." + Language.lang + ".";
}

/* getStr returns the translation for the given string based on the language of the app and
   translation provided in the dictionary for that language. If no translation is provided,
   No Translation will be shown*/
Language.getStr = function(str) {
    let translatedStr = eval(Language.getLanguage() + str);
    if (translatedStr != null) {
        return translatedStr;
    } else {
        return "No Translation";
    }
}
